import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@shawnsandy/first-paint/dist/css/libs/all.min.css";

import Main from "@/components/layout/main";
import Header from "@/components/layout/header";
import Nav from "@/components/layout/nav";
import Footer from "@/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <Header
          headerTitle="Page title"
          headerSubtitle="This is were I put my cool elevator pitch"
          data-style="cover"
        />
        <Main sidebar={true}>{children}</Main>
        <Footer>
          <div>Copyright © 2021 . All rights reserved.</div>
        </Footer>
      </body>
    </html>
  );
}
